#
# Pipeline that will build the ui project and publish the artifacts so 
# can be picked up by a release.
#
# Builds will be tagged with the pipeline start time in yyyyMMddHHmmss 
# and branch name.
#

trigger:
- main

pool: 'CMS Project' 

variables:    
  runDateTag: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]

jobs: 
- job: BuildAngular
  displayName: 'Publish Angular Project Artifacts'
  steps:

  # build the project
    - task: PowerShell@2
      displayName: 'Build Project'
      inputs:
        targetType: 'inline'
        script: |          
          npm i
          ng build --output-path $(Build.ArtifactStagingDirectory)/dist/asset-works

    # copy the output & source to the output directory  
    - task: CopyFiles@2
      displayName: 'Copy Output'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true

    # add build tags
    - task: PowerShell@2
      displayName: Add Build Tags
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "##vso[build.addbuildtag]$(runDateTag)"
          Write-Host "##vso[build.addbuildtag]$(Build.SourceBranchName)"
    
    # publish the artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
