#
# Pipeline that will build the ui project and publish the artifacts so 
# can be picked up by a release.
#
# Builds will be tagged with the pipeline start time in yyyyMMddHHmmss 
# and branch name.
#

trigger:
- none

pool: 'CMS Project' 

variables:    
  runDateTag: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]

jobs: 
- job: BuildAngular
  displayName: 'Publish Angular Project'
  steps:

    # build the project
    - task: PowerShell@2
      displayName: 'Build Project'
      inputs:
        targetType: 'inline'
        script: |
          npm i
          ng build

    # remove the node modules/dist folders as we'll be rebuilding this project in the release pipeline
    - task: DeleteFiles@1
      displayName: 'Delete Build Files'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          node_modules
          dist

    # copy the output & source to the output directory  
    - task: CopyFiles@2
      displayName: 'Copy Output'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'        

    # add build tags
    - task: PowerShell@2
      displayName: Add Build Tags
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "##vso[build.addbuildtag]$(runDateTag)"
          Write-Host "##vso[build.addbuildtag]$(Build.SourceBranchName)"
    
    # publish the artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
