#
# Pipeline that will build the ui project and publish the artifacts so 
# can be picked up by a release.
#
# Builds will be tagged with the pipeline start time in yyyyMMddHHmmss 
# and branch name.
#

trigger:
- none

pool:
  vmImage: ubuntu-latest # todo change to self-hosted agent

variables:    
  runDateTag: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]

jobs: 
- job: BuildAngular
  steps:

  # install angular cli & build the project
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          npm install -g @angular/cli
          npm i
          ng build

    # copy the output & source to the output directory  
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true

    # add build tags
    - task: PowerShell@2
      displayName: Add Build Tags
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "##vso[build.addbuildtag]$(runDateTag)"
          Write-Host "##vso[build.addbuildtag]$(Build.SourceBranchName)"
    
    # publish the artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
