sonar.host.url=http://51.142.178.175:9001/
sonar.login=admin
sonar.password=Tekmindz@0987
sonar.projectKey=WebFrontend
sonar.projectName=WebFrontend
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
