export const environment = {
  production: true,
  origin: 'https://app-eus-cms-internal-portalapi-dev.azurewebsites.net/',
  originAuth: 'https://app-eus-cms-internal-usermgmt-dev.azurewebsites.net/',
  localOrigin: 'https://app-eus-cms-internal-usermgmt-dev.azurewebsites.net/api/',
  originDiagnostic: 'https://app-eus-cms-internal-ocpp-dev.azurewebsites.net/',
  assetLocalOrigin: 'https://app-eus-cms-internal-assets-dev.azurewebsites.net/api/',
  reportLocalOrigin: 'https://app-eus-cms-internal-report-dev.azurewebsites.net/api/',
  AssetPricing: 'https://pricing-service.azurewebsites.net/api/',
  imagePath: '',
  onProd: 0,
  isPlatform: 'Production Platform',
  isPlatformMsg: '',
  versionNumber: 'Dev v 1.0',
  PASSWORD_PRIVATE_KEY: '',
}
