export const environment = {
  production: true,
  origin: 'https://qa-rest-service.azurewebsites.net/',
  originAuth: 'https://qa-user-mgmt-service.azurewebsites.net/',
  localOrigin: 'https://qa-user-mgmt-service.azurewebsites.net/api/',
  originDiagnostic: ' https://qa-ocpp-core.azurewebsites.net/',
  assetLocalOrigin: 'https://qa-assets-service.azurewebsites.net/api/',
  reportLocalOrigin: 'https://qa-report-service.azurewebsites.net/api/',
  imagePath: '',
  onProd: 0,
  isPlatform: 'Production Platform',
  isPlatformMsg: '',
  versionNumber: 'Dev v 1.0',
  PASSWORD_PRIVATE_KEY: '',
}
