export const environment = {
  production: true,
  origin: 'https://asw-portal-rest-service.azurewebsites.net/',
  originAuth: 'https://user-mgmt-service.azurewebsites.net/',
  localOrigin: 'https://user-mgmt-service.azurewebsites.net/api/',
  originDiagnostic: 'https://ocpp-core.azurewebsites.net/',
  assetLocalOrigin: 'https://assets-service.azurewebsites.net/api/',
  reportLocalOrigin: 'https://asw-report-service.azurewebsites.net/api/',
  AssetPricing: 'https://pricing-service.azurewebsites.net/api/',
  imagePath: '',
  onProd: 0,
  isPlatform: 'Production Platform',
  isPlatformMsg: '',
  versionNumber: 'Dev v 1.0',
  PASSWORD_PRIVATE_KEY: '',
}
